title: Drew Clark # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a graduate student at the University of Washington pursuing my Masters in Electrical and Computer Engineering, 
  planning to graduate December 2019. My studies have primarily involved machine learning and robotics, 
  with extensive work in computer vision applications.

  Prior to graduate school, I earned a Bachelor's in Aerospace Engineering and worked 2.5 years performing multiple 
  engineering disciplines surrounding diesel fuel systems.

  I'm currently seeking positions in machine learning or robotics applications. If you’d like to learn more about me 
  and discuss potential positions, please reach out via LinkedIn or email (drewc747@gmail.com).  
  <br><br>
  The purpose of this portfolio is to demonstrate various skills and techniques in the realm of Machine Learning and Robotics.
  Each project is attempted to be in a tutorial format to demonstrate understanding of the concepts, as well as implamentation. 
  Throughout the projects, I demonstrate skills such as Python (and various libraries), C++, TensorFlow, Keras, PyTorch, ROS. 
  Each project begins by listing the skills and techniques covered in that portion, and also has a link to the github repository 
  containing the full code used to generate all results and plots covered in the project.
  <br><br>
  <a href="https://www.linkedin.com/in/drewc747/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
