title: Drew Clark # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a recent graduate from the University of Washington with a MS in Electrical and Computer Engineering. My studies 
  have primarily involved machine learning and robotics, with extensive work in computer vision applications. 
  <br><br>
  If you’d like to learn more about me or discuss potential positions, please reach out via LinkedIn or email (drewc747@gmail.com).  
  <br><br>
  <a href="https://www.linkedin.com/in/drewc747/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-150272481-1 # your Google Analytics tracking ID here
