title: Drew Clark # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a graduate student at the University of Washington pursuing my Masters in Electrical and Computer Engineering, 
  planning to graduate December 2019. My studies have primarily involved machine learning and robotics, 
  with extensive work in computer vision applications.

  I'm currently seeking positions in machine learning or robotics applications. If you’d like to learn more about me 
  and discuss potential positions, please reach out via LinkedIn or email (drewc747@gmail.com).  
  <br><br>
  The purpose of this portfolio is to demonstrate various skills and techniques in the realm of Machine Learning and Robotics 
  tutorial style projects to demonstrate understanding of the concepts, as well as implementation.
  <br><br>
  <a href="https://www.linkedin.com/in/drewc747/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-150272481-1 # your Google Analytics tracking ID here
